
title: Chilicoder`s blog
author: Chilicoder
twitter_username: chilicoder
github_username:  chilicoder

# Build settings
markdown: kramdown
theme: minima
  disqus:
    shortname: chilicoder.disqus.com
